// <auto-generated />
using System;
using AgentRp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgentRp.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20260424161256_AddAiProvidersAndModels")]
    partial class AddAiProvidersAndModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgentRp.Data.AiModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("PlanningSettingsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProviderModelId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Repository")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("UseJsonSchemaResponseFormat")
                        .HasColumnType("bit");

                    b.Property<string>("WritingSettingsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled", "SortOrder");

                    b.HasIndex("ProviderId", "ProviderModelId")
                        .IsUnique();

                    b.ToTable("AiModels");
                });

            modelBuilder.Entity("AgentRp.Data.AiProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountId")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BaseEndpoint")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastDiscoveredUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastDiscoveryError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastMetricsError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastMetricsRefreshUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ManagementApiKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProjectId")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ProviderKind")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("TeamId")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("IsEnabled", "SortOrder");

                    b.ToTable("AiProviders");
                });

            modelBuilder.Entity("AgentRp.Data.AiProviderMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("MetricKind")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RefreshedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId", "MetricKind");

                    b.ToTable("AiProviderMetrics");
                });

            modelBuilder.Entity("AgentRp.Data.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("JsonValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("AgentRp.Data.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EditedFromMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GenerationMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageKind")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SourceProcessRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SpeakerCharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EditedFromMessageId");

                    b.HasIndex("ThreadId", "CreatedUtc");

                    b.HasIndex("ThreadId", "ParentMessageId");

                    b.HasIndex("ThreadId", "SourceProcessRunId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("AgentRp.Data.ChatStory", b =>
                {
                    b.Property<Guid>("ChatThreadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CharactersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("HistoryJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SceneJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoryContextJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("ChatThreadId");

                    b.ToTable("ChatStories");
                });

            modelBuilder.Entity("AgentRp.Data.ChatThread", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActiveLeafMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsStarred")
                        .HasColumnType("bit");

                    b.Property<string>("SelectedAgentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("SelectedAiModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SelectedSpeakerCharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SelectedAiModelId");

                    b.HasIndex("UpdatedUtc");

                    b.HasIndex("IsStarred", "UpdatedUtc");

                    b.ToTable("ChatThreads");
                });

            modelBuilder.Entity("AgentRp.Data.ProcessRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActorCharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssistantMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContextJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PlanningCompletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PlanningStartedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProseCompletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProseStartedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Stage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TargetMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ThreadId", "TargetMessageId");

                    b.HasIndex("ThreadId", "UserMessageId");

                    b.ToTable("ProcessRuns");
                });

            modelBuilder.Entity("AgentRp.Data.ProcessStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconCssClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("InputTokenCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("OutputTokenCount")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ProcessRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TotalTokenCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProcessRunId", "SortOrder");

                    b.ToTable("ProcessSteps");
                });

            modelBuilder.Entity("AgentRp.Data.StoryChatAppearanceEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppearanceJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CoveredThroughMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CoveredThroughUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SelectedLeafMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ThreadId", "CoveredThroughMessageId");

                    b.HasIndex("ThreadId", "CreatedUtc");

                    b.HasIndex("ThreadId", "SelectedLeafMessageId");

                    b.ToTable("StoryChatAppearanceEntries");
                });

            modelBuilder.Entity("AgentRp.Data.StoryChatSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CoveredThroughMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CoveredThroughUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("IncludedMessageIdsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SelectedLeafMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ThreadId", "CoveredThroughMessageId");

                    b.HasIndex("ThreadId", "CreatedUtc");

                    b.HasIndex("ThreadId", "SelectedLeafMessageId");

                    b.ToTable("StoryChatSnapshots");
                });

            modelBuilder.Entity("AgentRp.Data.AiModel", b =>
                {
                    b.HasOne("AgentRp.Data.AiProvider", "Provider")
                        .WithMany("Models")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("AgentRp.Data.AiProviderMetric", b =>
                {
                    b.HasOne("AgentRp.Data.AiProvider", "Provider")
                        .WithMany("Metrics")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("AgentRp.Data.ChatMessage", b =>
                {
                    b.HasOne("AgentRp.Data.ChatThread", "Thread")
                        .WithMany("Messages")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("AgentRp.Data.ChatStory", b =>
                {
                    b.HasOne("AgentRp.Data.ChatThread", "Thread")
                        .WithOne("Story")
                        .HasForeignKey("AgentRp.Data.ChatStory", "ChatThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("AgentRp.Data.ChatThread", b =>
                {
                    b.HasOne("AgentRp.Data.AiModel", "SelectedAiModel")
                        .WithMany()
                        .HasForeignKey("SelectedAiModelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SelectedAiModel");
                });

            modelBuilder.Entity("AgentRp.Data.ProcessRun", b =>
                {
                    b.HasOne("AgentRp.Data.ChatThread", "Thread")
                        .WithMany("ProcessRuns")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("AgentRp.Data.ProcessStep", b =>
                {
                    b.HasOne("AgentRp.Data.ProcessRun", "Run")
                        .WithMany("Steps")
                        .HasForeignKey("ProcessRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("AgentRp.Data.StoryChatAppearanceEntry", b =>
                {
                    b.HasOne("AgentRp.Data.ChatThread", "Thread")
                        .WithMany("AppearanceEntries")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("AgentRp.Data.StoryChatSnapshot", b =>
                {
                    b.HasOne("AgentRp.Data.ChatThread", "Thread")
                        .WithMany("Snapshots")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("AgentRp.Data.AiProvider", b =>
                {
                    b.Navigation("Metrics");

                    b.Navigation("Models");
                });

            modelBuilder.Entity("AgentRp.Data.ChatThread", b =>
                {
                    b.Navigation("AppearanceEntries");

                    b.Navigation("Messages");

                    b.Navigation("ProcessRuns");

                    b.Navigation("Snapshots");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("AgentRp.Data.ProcessRun", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
