// <auto-generated />
using System;
using AgentRp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgentRp.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgentRp.Data.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("JsonValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("AgentRp.Data.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EditedFromMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GenerationMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageKind")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SourceProcessRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SpeakerCharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EditedFromMessageId");

                    b.HasIndex("ThreadId", "CreatedUtc");

                    b.HasIndex("ThreadId", "ParentMessageId");

                    b.HasIndex("ThreadId", "SourceProcessRunId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("AgentRp.Data.ChatStory", b =>
                {
                    b.Property<Guid>("ChatThreadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CharactersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("HistoryJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SceneJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("ChatThreadId");

                    b.ToTable("ChatStories");
                });

            modelBuilder.Entity("AgentRp.Data.ChatThread", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActiveLeafMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsStarred")
                        .HasColumnType("bit");

                    b.Property<string>("SelectedAgentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("SelectedSpeakerCharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedUtc");

                    b.HasIndex("IsStarred", "UpdatedUtc");

                    b.ToTable("ChatThreads");
                });

            modelBuilder.Entity("AgentRp.Data.ProcessRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActorCharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssistantMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContextJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PlanningCompletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PlanningStartedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProseCompletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProseStartedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Stage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TargetMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ThreadId", "TargetMessageId");

                    b.HasIndex("ThreadId", "UserMessageId");

                    b.ToTable("ProcessRuns");
                });

            modelBuilder.Entity("AgentRp.Data.ProcessStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconCssClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProcessRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessRunId", "SortOrder");

                    b.ToTable("ProcessSteps");
                });

            modelBuilder.Entity("AgentRp.Data.StoryChatAppearanceEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppearanceJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CoveredThroughMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CoveredThroughUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SelectedLeafMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ThreadId", "CoveredThroughMessageId");

                    b.HasIndex("ThreadId", "CreatedUtc");

                    b.HasIndex("ThreadId", "SelectedLeafMessageId");

                    b.ToTable("StoryChatAppearanceEntries");
                });

            modelBuilder.Entity("AgentRp.Data.StoryChatSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CoveredThroughMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CoveredThroughUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("IncludedMessageIdsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SelectedLeafMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ThreadId", "CoveredThroughMessageId");

                    b.HasIndex("ThreadId", "CreatedUtc");

                    b.HasIndex("ThreadId", "SelectedLeafMessageId");

                    b.ToTable("StoryChatSnapshots");
                });

            modelBuilder.Entity("AgentRp.Data.ChatMessage", b =>
                {
                    b.HasOne("AgentRp.Data.ChatThread", "Thread")
                        .WithMany("Messages")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("AgentRp.Data.ChatStory", b =>
                {
                    b.HasOne("AgentRp.Data.ChatThread", "Thread")
                        .WithOne("Story")
                        .HasForeignKey("AgentRp.Data.ChatStory", "ChatThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("AgentRp.Data.ProcessRun", b =>
                {
                    b.HasOne("AgentRp.Data.ChatThread", "Thread")
                        .WithMany("ProcessRuns")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("AgentRp.Data.ProcessStep", b =>
                {
                    b.HasOne("AgentRp.Data.ProcessRun", "Run")
                        .WithMany("Steps")
                        .HasForeignKey("ProcessRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("AgentRp.Data.StoryChatAppearanceEntry", b =>
                {
                    b.HasOne("AgentRp.Data.ChatThread", "Thread")
                        .WithMany("AppearanceEntries")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("AgentRp.Data.StoryChatSnapshot", b =>
                {
                    b.HasOne("AgentRp.Data.ChatThread", "Thread")
                        .WithMany("Snapshots")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("AgentRp.Data.ChatThread", b =>
                {
                    b.Navigation("AppearanceEntries");

                    b.Navigation("Messages");

                    b.Navigation("ProcessRuns");

                    b.Navigation("Snapshots");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("AgentRp.Data.ProcessRun", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
